name: .NET Core CI CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1
    - name: Install dependencies
      run: dotnet restore /apis/poi/poi.sln
    - name: Build
      run: dotnet build /apis/poi/poi.sln --configuration Release --no-restore
#    - name: Test dotnet code projects
#      run: dotnet test MyProject/MyProject.Tests/MyProject.Tests.csproj --configuration ${{ env.buildConfiguration }}
#
