name: .NET Core CI CD

on:
  push:
    branches: [ master ]
    paths-ignore: 
    - '/apis/trips/**'
    - '/apis/user-java**'
    - 'apis/userprofile/**'
  pull_request:
    branches: [ master ]
    paths-ignore: 
    - '/apis/trips/**'
    - '/apis/user-java**'
    - 'apis/userprofile/**'

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      IMAGE_NAME: githubactions
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1
#    - name: Install dependencies
#      run: dotnet restore ./apis/poi/web/poi.csproj
#    - name: Build
#      run: dotnet build ./apis/poi/web/poi.csproj --configuration Release --no-restore
#    - name: Test dotnet code projects
#      run: dotnet test ./apis/poi/tests/UnitTests/*.csproj --configuration Release
#    - name: Build poi image
#      run: docker build ./apis/poi/ --file ./apis/poi/web/Dockerfile --tag $IMAGE_NAME
  acr_build:
    runs-on: ubuntu-latest
    steps:
    - name: ACR build
      id: acr
      uses: Azure/acr-build@main
      with:
#        service_principal: ${{ secrets.service_principal }}
#        service_principal_password: ${{ secrets.service_principal_password }}
#        tenant: ${{ secrets.tenant }}
#        registry: ${{ secrets.registry }}
#        repository: ${{ secrets.repository }}
#        image: poi
#        folder: /apis/poi
#        dockerfile: ./web/dockerfile
        service_principal: http://GitHub-Actions-bsl
        service_principal_password: ${{ secrets.service_principal_password }}
        tenant: ec18604c-74ea-44f5-bc46-e737b5284cfe
        registry: openhackwpn4z9r3acr.azurecr.io
        repository: devopsoh/api-poi
        image: poi
        folder: /apis/poi
        dockerfile: /apis/poi/web/dockerfile
